import React, { useState } from 'react';
import BlocksCanvas from './BlocksCanvas';
import ScreenEditor from './editor/ScreenEditor';
import ScreensSidebar from './studio/ScreensSidebar';
import TemplateSelectorModal from './studio/TemplateSelectorModal';
import AIGeneratorModal from '../ai/AIGeneratorModal';
import { toFreeform } from './editor/geometry';

export default function ScreensManager({ 
  screens, displays = [], loops = [], onSaveScreen, onDeleteScreen, onImportScreen, onPushScreen, events, feeds, members, chores, rewards, onToggleChore, onEditChore, onDeleteChore, onRedeemReward, onEditReward, onDeleteReward, clientMode, isAdmin
}) {
  const [selectedScreenId, setSelectedScreenId] = useState(screens[0]?.id || null);
  const [isEditing, setIsEditing] = useState(false);
  const [isAIModalOpen, setIsAIModalOpen] = useState(false);
  const [isTemplateModalOpen, setIsTemplateModalOpen] = useState(false);

  const [screenForm, setScreenForm] = useState({
    name: '',
    description: '',
    orientation: 'landscape',
    resolution: '1080p',
    background_type: 'color',
    background_value: '#090D16',
    custom_css: '',
    blocks: []
  });

  const selectedScreen = screens.find(s => s.id === selectedScreenId) || screens[0];

  const handleStartNew = () => {
    setScreenForm({
      name: 'New Custom Screen',
      description: 'Custom modular workspace',
      orientation: 'landscape',
      resolution: '1080p',
      background_type: 'color',
      background_value: '#090D16',
      custom_css: '',
      blocks: [
        { type: 'calendar_month', pos_x: 0, pos_y: 0, width: 7, height: 12, config: {} },
        { type: 'chores_tracker', pos_x: 7, pos_y: 0, width: 5, height: 12, config: { showRewards: true } }
      ]
    });
    setIsEditing(true);
  };

  const handleEditSelected = () => {
    if (!selectedScreen) return;
    setScreenForm({
      id: selectedScreen.id,
      name: selectedScreen.name,
      description: selectedScreen.description || '',
      orientation: selectedScreen.orientation || 'landscape',
      resolution: selectedScreen.resolution || '1080p',
      background_type: selectedScreen.background_type || 'color',
      background_value: selectedScreen.background_value || '#090D16',
      custom_css: selectedScreen.custom_css || '',
      blocks: (selectedScreen.blocks || []).map(toFreeform)
    });
    setIsEditing(true);
  };
  const handleApplyPresetTemplate = (tpl) => {
    setScreenForm(prev => ({
      ...prev,
      name: prev.name && prev.name !== 'New Custom Screen' ? prev.name : tpl.name,
      description: tpl.description || prev.description,
      orientation: tpl.orientation || 'landscape',
      resolution: tpl.resolution || '1080p',
      background_type: tpl.background_type || 'color',
      background_value: tpl.background_value || '#090D16',
      custom_css: tpl.custom_css || '',
      blocks: (tpl.blocks || []).map(b => ({
        ...b,
        x_percent: b.x_percent ?? 0,
        y_percent: b.y_percent ?? 0,
        w_percent: b.w_percent ?? 50,
        h_percent: b.h_percent ?? 50,
        config: b.config ? { ...b.config } : {}
      }))
    }));
    setIsEditing(true);
  };

  const handleApplyAIScreen = (aiScreen) => {
    setScreenForm({
      name: aiScreen.name || 'AI Generated Screen',
      description: aiScreen.description || 'Generated by AI',
      orientation: aiScreen.orientation || 'landscape',
      resolution: '1080p',
      background_type: aiScreen.background_type || 'color',
      background_value: aiScreen.background_value || '#090D16',
      custom_css: aiScreen.custom_css || '',
      blocks: (aiScreen.blocks || []).map(b => ({
        ...b,
        x_percent: b.x_percent ?? 0,
        y_percent: b.y_percent ?? 0,
        w_percent: b.w_percent ?? 50,
        h_percent: b.h_percent ?? 50,
        config: b.config ? { ...b.config } : {}
      }))
    });
    setIsEditing(true);
  };

  const handleSave = async (e) => {
    if (e && e.preventDefault) e.preventDefault();
    if (!screenForm.name.trim()) return;
    const normalized = { ...screenForm, blocks: (screenForm.blocks || []).map(toFreeform) };
    await onSaveScreen(normalized);
    setIsEditing(false);
  };

  const addBlock = (type) => {
    const newBlock = {
      type,
      x_percent: 5,
      y_percent: 5,
      w_percent: 30,
      h_percent: 25,
      config: type === 'chores_tracker' ? { showRewards: true } : {}
    };
    setScreenForm(prev => ({
      ...prev,
      blocks: [...prev.blocks, newBlock]
    }));
  };

  const removeBlock = (index) => {
    setScreenForm(prev => ({
      ...prev,
      blocks: prev.blocks.filter((_, i) => i !== index)
    }));
  };

  const updateBlockGeometry = (index, patch) => {
    setScreenForm(prev => ({
      ...prev,
      blocks: prev.blocks.map((b, i) => i === index ? { ...b, ...patch } : b)
    }));
  };

  const updateBlockConfig = (index, newConfig) => {
    setScreenForm(prev => ({
      ...prev,
      blocks: prev.blocks.map((b, i) => i === index ? { ...b, config: { ...b.config, ...newConfig } } : b)
    }));
  };


  return (
    <div className="flex h-full w-full bg-slate-950 overflow-hidden relative">
      <ScreensSidebar
        screens={screens}
        selectedScreen={selectedScreen}
        onSelect={(id) => { setSelectedScreenId(id); setIsEditing(false); }}
        onStartNew={handleStartNew}
        onOpenTemplates={() => setIsTemplateModalOpen(true)}
        onOpenAIDesigner={() => setIsAIModalOpen(true)}
        onEditSelected={handleEditSelected}
        onDeleteScreen={onDeleteScreen}
        onImport={onImportScreen}
      />

      <div className="flex-1 flex flex-col h-full overflow-hidden bg-slate-950">
        {isEditing ? (
          <ScreenEditor
            screenForm={screenForm}
            setScreenForm={setScreenForm}
            onSave={handleSave}
            onSaveAndPush={async (e) => {
              await handleSave(e);
              if (screenForm.id && onPushScreen) {
                await onPushScreen(screenForm.id);
              }
            }}
            onCancel={() => setIsEditing(false)}
            onOpenTemplates={() => setIsTemplateModalOpen(true)}
            onOpenAIDesigner={() => setIsAIModalOpen(true)}
            addBlock={addBlock}
            removeBlock={removeBlock}
            updateBlockGeometry={updateBlockGeometry}
            updateBlockConfig={updateBlockConfig}
            events={events}
            feeds={feeds}
            members={members}
            chores={chores}
            rewards={rewards}
            onToggleChore={onToggleChore}
            onEditChore={onEditChore}
            onDeleteChore={onDeleteChore}
            onRedeemReward={onRedeemReward}
            onEditReward={onEditReward}
            onDeleteReward={onDeleteReward}
            clientMode={clientMode}
          />
        ) : (
          <div className="flex-1 overflow-hidden bg-[#05070d]">
            {selectedScreen ? (
              <BlocksCanvas
                blocks={selectedScreen.blocks || []}
                orientation={selectedScreen.orientation || 'landscape'}
                backgroundType={selectedScreen.background_type || 'color'}
                backgroundValue={selectedScreen.background_value || '#090D16'}
                events={events}
                feeds={feeds}
                members={members}
                chores={chores}
                rewards={rewards}
                onToggleChore={onToggleChore}
                onEditChore={onEditChore}
                onDeleteChore={onDeleteChore}
                onRedeemReward={onRedeemReward}
                onEditReward={onEditReward}
                onDeleteReward={onDeleteReward}
                clientMode={clientMode}
              />
            ) : (
              <div className="flex-1 flex items-center justify-center text-slate-500 text-xs">Select or create a screen</div>
            )}
          </div>
        )}
      </div>

      <AIGeneratorModal
        isOpen={isAIModalOpen}
        onClose={() => setIsAIModalOpen(false)}
        onApplyScreen={handleApplyAIScreen}
        targetMode="screen"
        orientation={selectedScreen?.orientation || screenForm.orientation || 'landscape'}
      />

      <TemplateSelectorModal
        isOpen={isTemplateModalOpen}
        onClose={() => setIsTemplateModalOpen(false)}
        onSelectTemplate={handleApplyPresetTemplate}
        isAdmin={isAdmin}
      />
    </div>
  );
}
